### ISSUE TITLE
상반기 연구 일정

### ISSUE THREAD

**Issue by nadragon** [piani/Plan#1]
### 구체적인 주제 선정 (~5/30)
- [x] **주제 선정**
  - 범죄자 프로파일링
    - ex) 범죄자의 옛날 사진을 가지고, 나이 등이 변형된 모습이 예측된 사진을 만들 수 있다.
    - 변형된 요소를 입력하면, 원본 이미지를 StyleGAN으로 변형된 이미지로 만든다.
    - PRNet 으로 3D reconstruction
- [x] **개선 사항 찾기**
    - PRNet 키포인트 디텍션 성능 개선
</br>

### StyleGAN 파악 (~6/1)
- [ ] 논문읽기
- [x] ~~dataset 다운~~
  - 2TB로 너무 크고, 아직 training 시킬 일이 없어서 취소
- [ ] pretrained styleGAN 적용해서 result 보기
  - @yoee [코드보고 조금 메모한 것](https://github.com/yoee/DeepLearning/blob/master/ect/StyleGAN/%EC%9D%B4%ED%95%B4%ED%95%9C%20%EA%B2%83%2C%20%EA%B6%81%EA%B8%88%ED%95%9C%20%EA%B2%83.md)
  - 진행 중 ㅠㅠ
</br>

### Image-to-Image 변형 script 작성 (~6/2)
- [ ] 6/2 input -> [styleGAN + PRNet] -> result local로 보내기 script 작성
</br>

### TODO (~?)
- [ ] application 프로토타입 제작
</br>

### 중간 레포트 작성 (~6/14)
- [ ] 6/14 제출
